export const C = {
  sage: 'var(--bp-sage)',
  sageDark: 'var(--bp-sage-dark)',
  sageDeep: 'var(--bp-sage-deep)',
  sageLight: 'var(--bp-sage-light)',
  sagePale: 'var(--bp-sage-pale)',
  cream: 'var(--bp-cream)',
  creamLight: 'var(--bp-cream-light)',
  ivory: 'var(--bp-ivory)',
  brown: 'var(--bp-brown)',
  brownMid: 'var(--bp-brown-mid)',
  brownLight: 'var(--bp-brown-light)',
  caramel: 'var(--bp-caramel)',
  caramelLight: 'var(--bp-caramel-light)',
  rust: 'var(--bp-rust)',
  brownAlpha30: 'var(--bp-brown-alpha-30)',
  sageDeepAlpha30: 'var(--bp-sage-deep-alpha-30)',
  caramelLightAlpha30: 'var(--bp-caramel-light-alpha-30)',
  caramelLightAlpha40: 'var(--bp-caramel-light-alpha-40)',
  sagePaleAlpha80: 'var(--bp-sage-pale-alpha-80)',
  rustAlpha20: 'var(--bp-rust-alpha-20)',
  rustAlpha30: 'var(--bp-rust-alpha-30)',
  rustAlpha40: 'var(--bp-rust-alpha-40)',
  sageDarkAlpha50: 'var(--bp-sage-dark-alpha-50)'
};
